apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-vaultkubenertes-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-vaultkubenertes-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-test-4
        namespace: flux-test-4
      chart: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: carrier
      component_type: peer
      namespace: carrier-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: a139978f9f86c4d98a127b8a487bda6b-723900320.us-east-1.elb.amazonaws.com:20001
      authpath: test-4carrier-net-auth
      policy: vault-crypto-peer-carrier-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://A17845AFBF2DFCC97DBA0930C3BAFD24.gr7.us-east-1.eks.amazonaws.com
