apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-cacerts-job
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: store-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: store
      component_name: store-net
      namespace: store-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://a581b6f33f36145c9b381ff3c4012cd6-1055042004.us-east-1.elb.amazonaws.com:8200
      authpath: devstore-net-auth
      secretcryptoprefix: secretsfront/data/crypto/peerOrganizations/store-net/ca
      secretcredentialsprefix: secretsfront/data/credentials/store-net/ca/store
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=US/ST=New York/L=New York/O=Store/CN=ca.store-net.org4ambassador.blockchaincloudpoc.com
