apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-vaultkubenertes-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-vaultkubenertes-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-test-4
        namespace: flux-test-4
      chart: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: supplychain
      component_type: orderer
      namespace: supplychain-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: a581b6f33f36145c9b381ff3c4012cd6-1055042004.us-east-1.elb.amazonaws.com:8200
      authpath: test-4supplychain-net-auth
      policy: vault-crypto-orderer-supplychain-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://A17845AFBF2DFCC97DBA0930C3BAFD24.gr7.us-east-1.eks.amazonaws.com
