apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cacerts-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-test-networkv2
        namespace: flux-test-networkv2
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: supplychain
      component_name: supplychain-net
      namespace: supplychain-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://a581b6f33f36145c9b381ff3c4012cd6-1055042004.us-east-1.elb.amazonaws.com:8200
      authpath: test-networkv2supplychain-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/supplychain-net/ca/supplychain
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-net.org1ambassador.blockchaincloudpoc.com
